### ISSUE TITLE
It must be me... but it just doesn't work.

### ISSUE THREAD

**Issue by TheBaronHimself** [lingo/sublime-fscompletion#14]
**Hey Luke**

I love the idea of this plugin and it would really help me with my workflow. Unfortunately, I just cannot get it to work. 

I'm use Sublime Text 3. Whenever I type the beginning of a path that I know exists (such as /Users/ or  ~/) I just won't get any autocompletion suggestions. Control + space just throws the message "No available completion", while the package's own shortcut won't do anything, altogether.

I must be missing something... Are there any specific conditions that need to be met for this plugin to work? Does it only work for certain file types?

Best wishes, 
Simon-Claudius

**Comment by TheBaronHimself** [comment]
I'm on OS X 10.10, by the way.

**Comment by lingo** [comment]
If you could turn on debug mode and paste me the ouptut from Sublime's terminal, that could be very helpful.

1. Turn on debug mode.  Find the User settings for this plugin: Menu `Preferences>Package Settings>Filesystem Autocompletion>User` Add the key `debug: true` to the JSON structure.
2. Open the sublime python console (Menu `View>Show Console`).
3. Place the cursor on a path in the editor and invoke the package using it's shortcut.
4. Copy the debug code and paste it here.

Thank you!

**Comment by TheBaronHimself** [comment]
**Hey Luke**

Here you go:
````
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "fscompletion in /Users/simon-claudius/Library/Application Support/Sublime Text 3/Installed Packages/FileSystem Autocompletion.sublime-package", line 124, in on_query_completions
  File "fscompletion in /Users/simon-claudius/Library/Application Support/Sublime Text 3/Installed Packages/FileSystem Autocompletion.sublime-package", line 90, in getviewcwd
  File "fscompletion in /Users/simon-claudius/Library/Application Support/Sublime Text 3/Installed Packages/FileSystem Autocompletion.sublime-package", line 36, in get_cwd_from_project
TypeError: 'NoneType' object is not subscriptable
````

Best wishes, 
Simon-Claudius

**Comment by lingo** [comment]
Should be fixed in latest release 0.3.1

**Comment by TheBaronHimself** [comment]
Unfortunately it's still not working. Here is the new console output:

````
get_view_cwd: <function get_cwd_from_project at 0x108ac3ef0> => None
FSAutocompletion: get_view_cwd: No view filename found
get_view_cwd: <function get_cwd_from_view at 0x10890d050> => None
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "fscompletion in /Users/simon-claudius/Library/Application Support/Sublime Text 3/Installed Packages/FileSystem Autocompletion.sublime-package", line 129, in on_query_completions
  File "fscompletion in /Users/simon-claudius/Library/Application Support/Sublime Text 3/Installed Packages/FileSystem Autocompletion.sublime-package", line 93, in get_view_cwd
  File "fscompletion in /Users/simon-claudius/Library/Application Support/Sublime Text 3/Installed Packages/FileSystem Autocompletion.sublime-package", line 63, in get_cwd_from_window
IndexError: pop from empty list
````

**Comment by lingo** [comment]
Please try again! :)

**Comment by TheBaronHimself** [comment]
Fixed. Thanks a lot :).
